### ISSUE TITLE
HTTP/2.0 403 Forbidden

### ISSUE THREAD

**Issue by helloxz** [chatgp/chatgpt-go#1]
按照demo的代码填写了自己的cookie，依然被CF拦截了。

返回了一段403的HTML代码，其中内容有：Checking if the site connection is secure

感觉还是没能绕过CF，或许需要添加更多的头部？

**Comment by idoubi** [comment]
1. NewClient 的时候，加上 WithUserAgent，使用你登录 ChatGPT 官网的 User-Agent

```go
cli = chatgpt.NewClient(
    chatgpt.WithDebug(true),
    chatgpt.WithTimeout(60*time.Second),
    chatgpt.WithCookies(cookies),
    chatgpt.WithUserAgent(userAgent),
)
```

2. 确保你使用 SDK 发起请求的 ip，跟你登录 ChatGPT 官网的 ip 一致

**Comment by helloxz** [comment]
已联系TG解决，感谢。

**Comment by Rehtt** [comment]
还是会出现403
