### ISSUE TITLE
get chat stream failed: send message failed: get accessToken failed: fetch new accessToken failed: parse response body failed exit status 1

### ISSUE THREAD

**Issue by qimo2020** [chatgp/chatgpt-go#2]
hello
What is the problem
![image](https://user-images.githubusercontent.com/60610664/219830704-504e56fa-a7bf-4c49-b6ce-fdfb27c0d859.png)

**Comment by idoubi** [comment]
maybe you don't have access to auto login?

check your cookies please and tell me have you found a cookie named '_puid', which is required.

**Comment by Patrick08T** [comment]
I also have this problem, and can not find '_puid' in my cookie.
how can i solve this problem?

**Comment by idoubi** [comment]
> 

_puid can only found in plus account
