### ISSUE TITLE
chatgpt default vs legacy

### ISSUE THREAD

**Issue by phudtran** [chatgp/chatgpt-go#3]
Is there a way to switch between the two? Currently can only use default.

![image](https://user-images.githubusercontent.com/22720475/219854692-71584c77-a2a0-405f-8094-8d7c28c5fa64.jpeg)

**Comment by idoubi** [comment]
I upgraded my sdk for supporting use different model.
in the new version, "text-davinci-002-render-sha" model is default, you can use another model when create client like:
```go
cli = chatgpt.NewClient(
  chatgpt.WithDebug(false),
  chatgpt.WithTimeout(60*time.Second),
  chatgpt.WithCookies(cookies),
  chatgpt.WithModel("text-davinci-002-render-paied"),
)
```
