### ISSUE TITLE
need help to select GPT-4 for a new chat

### ISSUE THREAD

**Issue by wawagit** [chatgp/chatgpt-go#7]
Any idea how to select GPT-4 model?

<img width="922" alt="gpt model selection" src="https://user-images.githubusercontent.com/1011569/225262453-17e9247d-9055-4925-a4c1-5c144d47ab40.png">

**Comment by wawagit** [comment]
A GET parameter seems selecting the model : [https://chat.openai.com/chat?model=gpt-4](https://chat.openai.com/chat?model=gpt-4)

**Comment by wawagit** [comment]
Is it enough to set the model like that?

```
cli := chatgpt.NewClient(
		chatgpt.WithDebug(true),
		chatgpt.WithTimeout(120*time.Second),
		chatgpt.WithCookies(cookies),
		chatgpt.WithModel("gpt-4"),
)

**Comment by denissslyu** [comment]
> 

enough.I have used this for one day.

**Comment by wawagit** [comment]
me too
